name: Tweet

on:
  workflow_dispatch:
  schedule:
    - cron: '15,45 * * * *' # Runs Bot every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i axios
      - run: npm i process
      - run: npm install sharp
      - run: npm i staticmaps
      - name: Install Google Fonts
        run: |
          wget -O ArialBlack.ttf https://github.com/gbif/analytics/raw/master/fonts/Arial%20Black.ttf
          mv ArialBlack.ttf /usr/share/fonts/
          fc-cache -fv
      - name: Instalar dependencias
        run: npm install twitter-api-v2
      - name: Run Bot
        env:
           CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
           CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
           ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: node index.js
        
