name: Tweet

on:
  workflow_dispatch:
  schedule:
    - cron: '15,45 * * * *' # Runs Bot every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia la versión de Node.js según tus necesidades
      - name: Instalar dependencias
        run: npm install twitter-api-v2
      #  env:
      #    CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      #    CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      #    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #    ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      - name: Run Bot
        run: echo 'Hola'
      #- run: node index.js
